const PRELOADER_BOOLEAN = 'PRELOADER_BOOLEAN';
const DOWNLOAD_FINISHED = 'DOWNLOAD_FINISHED';
const COUNT_OFFSET = 'COUNT_OFFSET';
const LIST_CREATION = 'LIST_CREATION';
const SEARCH_REQUEST = 'SEARCH_REQUEST'
const TARGET_TRANSFER = 'TARGET_TRANSFER'
const CHANGE_PAGE = 'CHANGE_PAGE'
const SAVE_RESPONSE = 'SAVE_RESPONSE'
const SAVE_ID = 'SAVE_ID'
const SAVE_PROFILE_INFO = 'SAVE_PROFILE_INFO'

export {PRELOADER_BOOLEAN, DOWNLOAD_FINISHED, COUNT_OFFSET, LIST_CREATION, SEARCH_REQUEST, TARGET_TRANSFER, CHANGE_PAGE, SAVE_RESPONSE, SAVE_ID, SAVE_PROFILE_INFO}