const PRELOADER_BOOLEAN = 'PRELOADER_BOOLEAN';
const DOWNLOAD_FINISHED = 'DOWNLOAD_FINISHED';
const COUNT_OFFSET = 'COUNT_OFFSET';
const ARRAY_CREATION = 'ARRAY_CREATION';

export {PRELOADER_BOOLEAN, DOWNLOAD_FINISHED, COUNT_OFFSET, ARRAY_CREATION}